; ============================================================
;  TRoyTel™ — Asterisk PBX: voicemail.conf
;  © TRoy Group™
; ============================================================

[general]
format=wav49|gsm|wav
serveremail=groupoftroy@gmail.com
attach=yes
skipms=3000
maxsilence=10
silencethreshold=128
maxlogins=3
emaildateformat=%A, %B %d, %Y at %r
sendvoicemail=yes

[zonemessages]
darwin=Australia/Darwin|'vm-received' q 'digits/at' IMp

[troy-vm]
; Mailbox => password,Full Name,email,pager_email,options
001 => 1234,TRoy Group CEO,groupoftroy@gmail.com,,tz=darwin|delete=no
100 => 1234,TRoy Maritime Agency,troymaritimeagency@gmail.com,,tz=darwin|delete=no
200 => 1234,TRoyGo Travel Agency,troytravelagency@gmail.com,,tz=darwin|delete=no
300 => 1234,TRoy Trading Agency,troytradingagency@gmail.com,,tz=darwin|delete=no
